### PR TITLE
Change support chat URL

### PR DESCRIPTION
**Pull request by Yash-Garg**

### CODE REVIEW

**Comment by Akianonymus** [comment]
@Yash-Garg pro

**Comment by Yash-Garg** [comment]
> @Yash-Garg pro

bsdk ;-;

**Comment by krypticallusion** [comment]
@Yash-Garg Wew

**Comment by ATechnoHazard** [comment]
@krypticallusion Wew

**Comment by Akianonymus** [comment]
@ATechnoHazard Wew 3

**Comment by icodelifee** [comment]
@Akianonymus Wew 4

**Comment by ATechnoHazard** [comment]
@icodelifee

**Comment by songotenks69** [comment]
@icodelifee Wew 5

**Comment by ATechnoHazard** [comment]
@songotenks69 Do you want to see fat guy brown

**Comment by arthurof** [comment]
@ATechnoHazard Lil

**Comment by Yash-Garg** [comment]
Also the pro guys posting comments above, @icodelifee asked me to make a PR for this. #BlameIchuLife

**Comment by Akianonymus** [comment]
@Yash-Garg because you pro reeee !

**Pull request merged**
